:Author: drWack413
:Email: jmachadoat4@gmail.com
:Date: 26/02/2018
:Revision: version# 2
:License: Public Domain

= Project: {Arduino Pong}
using an 8x8 LED matrix, make a simple pong game

== Step 1: Installation

1. Open this file
2. Edit as you like
3. Release to the World!
make sure to do the wiring right tho

== Step 2: Assemble the circuit

look at rowColScan_bb.png 

Source:
https://www.arduino.cc/en/uploads/Tutorial/rowColScan_bb.png


== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Pong_with_class          => Arduino sketch folder
  ├── Pong_with_class.ino => main Arduino file
  ├── rowCalScann_bb.png  => a wiring layout
  ├── myLib.h             => personal library, mostly for handling the led matrix elegantly
  ├── Matrix.cpp          => custom class file for Matrixes
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a Memeware License.
if you use this, and see me in public, show me your freshest meme (good memes pls)

=== Contributing
To contribute to this project please contact drWack413 <jmachadoat4@gmail.com>
or do that ish on github idc dawg hit me with that pull req dawg

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| J4 | Touch Resistor | unknown     | 2        
| L1 | Jumper wires   | unknown     | 23
| MF | F2M wires      | unknown     | 16 
| A1 | Arduino Uno    | ABX00066    | 1        
| 88 | 8x8 Led Matrix | unknown     | 1
|===
(touch resistor can be swapped for any potentiometer)

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
